FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend/
COPY config/ ./config/

EXPOSE 5000

ENV FLASK_APP=backend/app.py

CMD ["python", "backend/app.py"]

